version: '3.7'

services:
  code-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # secrets:
    #   - API_KEY
    #   - AZURE_API_BASE
    networks:
      - internal-vnet
    environment:
      - OPENAI_INSTRUCT_MODEL_USE=False
      - OPENAI_API_TYPE=azure
      - OPENAI_MODEL=gpt-3.5-turbo-16k
      - OPENAI_INPUT_PRICE=0.003
      - OPENAI_OUTPUT_PRICE=0.004
      - AZURE_API_VERSION=2023-05-15
      - AZURE_DEPLOYMENT_ID=code-generation-tool-gpt-35-turbo-16k
      - OPENAI_RETRIES=2
      - OPENAI_RETRY_SLEEP_TIME=5
      - API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - AZURE_API_BASE=https://telecentro-openai.openai.azure.com
  
  gui:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 3000:80
      networks:
        - internal-vnet
      environment:
        - API_BASE_URL=code-generator:8000
 
# Secrets are only available with Docker swarm
#
# secrets:
#   API_KEY:
#     external: true
#   AZURE_API_BASE:
#     external: true
  
networks:
  internal-vnet:
    driver: bridge