[pytest]
addopts = -rsxX --showlocals --strict --ignore=tests/assets
; -r show extra test summary info as specified by chars: (s)skipped, (x)failed, (X)passed,
;    other options: (f)ailed, (E)error, (p)passed, (P)passed with output, (a)all except pP.

filterwarnings = ignore::DeprecationWarning
; This filters out deprecation warnings from pytest output.

markers =
    end_to_end: Tests the entire solution.

